sources:
  - MatrixSans-Regular.ufo
  - MatrixSansScreen-Regular.ufo
  - MatrixSansPrint-Regular.ufo
  - MatrixSansVideo-Regular.ufo
  - MatrixSansRaster-Regular.ufo
  - MatrixSansSmooth-Regular.ufo
familyName: Matrix Sans
buildVariable: false
removeOutlineOverlaps: false
autohintTTF: false
extraFontmakeArgs: --keep-direction
buildSmallCap: true
